remote-theme: just-the-docs
color_scheme: dark

title: Fallstudie App Ref. Card 01
description: Modul 169
nav_order: 2
has_children: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
